In [1]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
auto_mpg = fetch_ucirepo(id=9) 
  
# data (as pandas dataframes) 
X = auto_mpg.data.features 
y = auto_mpg.data.targets 
  
# metadata 
print(auto_mpg.metadata) 
  
# variable information 
print(auto_mpg.variables)

ModuleNotFoundError: No module named 'ucimlrepo'

In [2]:
pip install ucimlrepo

Collecting ucimlrepoNote: you may need to restart the kernel to use updated packages.
  Using cached ucimlrepo-0.0.3-py3-none-any.whl (7.0 kB)
Installing collected packages: ucimlrepo

Successfully installed ucimlrepo-0.0.3

In [3]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
auto_mpg = fetch_ucirepo(id=9) 
  
# data (as pandas dataframes) 
X = auto_mpg.data.features 
y = auto_mpg.data.targets 
  
# metadata 
print(auto_mpg.metadata) 
  
# variable information 
print(auto_mpg.variables)

{'uci_id': 9, 'name': 'Auto MPG', 'repository_url': 'https://archive.ics.uci.edu/dataset/9/auto+mpg', 'data_url': 'https://archive.ics.uci.edu/static/public/9/data.csv', 'abstract': 'Revised from CMU StatLib library, data concerns city-cycle fuel consumption', 'area': 'Other', 'tasks': ['Regression'], 'characteristics': ['Multivariate'], 'num_instances': 398, 'num_features': 7, 'feature_types': ['Real', 'Categorical', 'Integer'], 'demographics': [], 'target_col': ['mpg'], 'index_col': ['car_name'], 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1993, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5859H', 'creators': ['R. Quinlan'], 'intro_paper': None, 'additional_info': {'summary': 'This dataset is a slightly modified version of the dataset provided in the StatLib library.  In line with the use by Ross Quinlan (1993) in predicting the attribute "mpg", 8 of the original instances were removed because they had unknown values for the "mpg" attribute.  The original dataset is available in the file "auto-mpg.data-original".\r\n\r\n"The data concerns city-cycle fuel consumption in miles per gallon, to be predicted in terms of 3 multivalued discrete and 5 continuous attributes." (Quinlan, 1993)', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '    1. mpg:           continuous\r\n    2. cylinders:     multi-valued discrete\r\n    3. displacement:  continuous\r\n    4. horsepower:    continuous\r\n    5. weight:        continuous\r\n    6. acceleration:  continuous\r\n    7. model year:    multi-valued discrete\r\n    8. origin:        multi-valued discrete\r\n    9. car name:      string (unique for each instance)', 'citation': None}}
           name     role         type demographic description units  \
0  displacement  Feature   Continuous        None        None  None
1           mpg   Target   Continuous        None        None  None
2     cylinders  Feature      Integer        None        None  None
3    horsepower  Feature   Continuous        None        None  None
4        weight  Feature   Continuous        None        None  None
5  acceleration  Feature   Continuous        None        None  None
6    model_year  Feature      Integer        None        None  None
7        origin  Feature      Integer        None        None  None
8      car_name       ID  Categorical        None        None  None

  missing_values
0             no
1             no
2             no
3            yes
4             no
5             no
6             no
7             no
8             no

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
X.head()

,displacement,cylinders,horsepower,weight,acceleration,model_year,origin
0,307.0,8,130.0,3504,12.0,70,1
1,350.0,8,165.0,3693,11.5,70,1
2,318.0,8,150.0,3436,11.0,70,1
3,304.0,8,150.0,3433,12.0,70,1
4,302.0,8,140.0,3449,10.5,70,1

In [8]:
cols = ['MPG','Cylinders','Displacement','Horsepower','Weight',
                'Acceleration', 'Model Year', 'Origin']

FileNotFoundError: [Errno 2] No such file or directory: './auto_mpg.data'

In [10]:
data = df.copy()

NameError: name 'df' is not defined

In [11]:
df = pd.concat([X, pd.DataFrame(y, columns=['Target'])], axis=1)

In [12]:
data=df.copy()

In [13]:
data

,displacement,cylinders,horsepower,weight,acceleration,model_year,origin,Target
0,307.0,8,130.0,3504,12.0,70,1,NaN
1,350.0,8,165.0,3693,11.5,70,1,NaN
2,318.0,8,150.0,3436,11.0,70,1,NaN
3,304.0,8,150.0,3433,12.0,70,1,NaN
4,302.0,8,140.0,3449,10.5,70,1,NaN
...,...,...,...,...,...,...,...,...
393,140.0,4,86.0,2790,15.6,82,1,NaN
394,97.0,4,52.0,2130,24.6,82,2,NaN
395,135.0,4,84.0,2295,11.6,82,1,NaN
396,120.0,4,79.0,2625,18.6,82,1,NaN
397,119.0,4,82.0,2720,19.4,82,1,NaN

In [15]:
df.head()

,displacement,cylinders,horsepower,weight,acceleration,model_year,origin,Target
0,307.0,8,130.0,3504,12.0,70,1,NaN
1,350.0,8,165.0,3693,11.5,70,1,NaN
2,318.0,8,150.0,3436,11.0,70,1,NaN
3,304.0,8,150.0,3433,12.0,70,1,NaN
4,302.0,8,140.0,3449,10.5,70,1,NaN